assert(SMODS.load_file("jokers.lua"))()
-- assert(SMODS.load_file("backs.lua"))()
-- assert(SMODS.load_file("blinds.lua"))()
-- assert(SMODS.load_file("seals.lua"))()
assert(SMODS.load_file("vouchers.lua"))()
-- assert(SMODS.load_file("enhancements.lua"))()
-- assert(SMODS.load_file("tarots.lua"))()
-- assert(SMODS.load_file("editions.lua"))()
-- assert(SMODS.load_file("spectrals.lua"))()
-- assert(SMODS.load_file("challenges.lua"))()
-- assert(SMODS.load_file("stakes.lua"))()
-- assert(SMODS.load_file("rarities.lua"))()
-- assert(SMODS.load_file("stickers.lua"))()
assert(SMODS.load_file("atlas.lua"))()